### ISSUE TITLE
[v4] Bug when adding onAnimate prop

### ISSUE THREAD

**Issue by Alaa-Ben** [gorhom/react-native-scroll-bottom-sheet#1118]
# Bug

Hi ! First of all, thanks for the effort !
I've discovered a weird behaviour:
the `index` prop is supposed to be the initial index, which means that the bottom sheet shouldn't animate back to this index on each render, which works correctly. Expect if `onAnimate` prop is added. (even if it's a noop func () => {})
So yeah, if `onAnimate` prop is added, it animates back to the initial index.

## Environment info

| Library                                         | Version |
| -------------------------------| --------|
| @gorhom/bottom-sheet            | 4.4.5     |
| react-native                                | 0.67.2    |
| react-native-reanimated           | 2.4.1       |
| react-native-gesture-handler  | 2.1.2       |

## Steps To Reproduce
1. Add onAnimate prop (even with no op func () => {})
2. Let's suppose initial index = 0, drag the sheet to another index (1 for example)
3. Trigger a render (a button, a setInterval that triggers a useState, whatever)
4. Watch the sheet animate back from 1 to 0

Describe what you expected to happen:
As index is supposed to be the initial snap, it's not supposed to move on a rerender (which works correctly if onAnimate is not provided)

## Reproducible sample code

Just copy paste [the doc code](https://gorhom.github.io/react-native-bottom-sheet/components/bottomsheetscrollview/)
and only add `onAnimate={() => {}}` to the bottom sheet.

Thanks !

**Comment by rawatnaresh** [comment]
I reported a similar issue [here](https://github.com/gorhom/react-native-bottom-sheet/issues/1144). Didn't know it was already reported. I had to use `onChange` instead of `onAnimate`

**Comment by Alaa-Ben** [comment]
Still happening.

**Comment by cepintos** [comment]
Hi! I fixed this by wrapping my onAnimate callback with a `useCallback`

**Comment by Buk1m** [comment]
`useCallback` does not fix the problem entirely. Bottom sheet collapses whenever useCallback dependencies change and new instance of function is passed to onAnimate.

**Comment by zunkelty** [comment]
For me, `onAnimate` fires with `toIndex: -1` even when the modal is not closing. 

I am using the [Bottom Sheet Modal](https://gorhom.github.io/react-native-bottom-sheet/modal) with a [BottomSheetTextInput](https://gorhom.github.io/react-native-bottom-sheet/components/bottomsheettextinput). Every time I focus the TextInput, the `onAnimate` callback is triggered with `toIndex: -1` even though the actual modal is does not close.

Could this be related or does somebody know a fix to my problem?
