### ISSUE TITLE
[v4] Crash when use handleComponent with keyboard

### ISSUE THREAD

**Issue by Lucasark** [gorhom/react-native-scroll-bottom-sheet#1351]
# Bug

When try pull down/up handleComponent it show a error and freeze application, video below:

https://user-images.githubusercontent.com/31750882/233798288-05c1e9f0-732e-471a-9788-0534d8cdcb12.mp4

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5  |
| react-native                    | 0.69.4  |
| react-native-reanimated         | 3.1.0   |
| react-native-gesture-handler    | 2.5.0   |

## Steps To Reproduce

Video attech

Describe what you expected to happen:

Not crash :D

## Reproducible sample code

Using example from this repo.

Ps.: Example is too up-date, I needed todo fews steps to complete build.

**Comment by Lucasark** [comment]
Temporary Workaround:

On handle I am using Presseble with Keyboard.dismiss();

```
      <Pressable style={{
        paddingHorizontal: 16,
        paddingVertical: 5,
        
      }} onPressIn={() => Keyboard.dismiss()}> 

     {...}
```

**Comment by sussertod891015** [comment]
same here, even I pass the props `enablePanDownToClose={false}`,  sometimes I can scroll BottomSheet, and will cause error like above, then app crashed.
![IMG_6245](https://user-images.githubusercontent.com/10465307/235100449-de14edfc-8bfd-41e4-9645-c0042fef313b.png)

**Comment by cctipgit** [comment]
I have the same problem, wait

**Comment by gorhom** [comment]
this should be fixed in v5, https://github.com/gorhom/react-native-bottom-sheet/pull/1346

**Comment by batuhansahan** [comment]
hello @gorhom i just updated the library to latest version still this error is happening

`"@gorhom/bottom-sheet": "5.0.0-alpha.1",`
```
  "error": {
    "message": "Tried to synchronously call a non-worklet function on the UI thread.\n\nPossible solutions are:\n  a) If you want to synchronously execute this method, mark it as a worklet\n  b) If you want to execute this function on the JS thread, wrap it using `runOnJS`",
    "name": "ReanimatedError",
    "jsEngine": "reanimated"
  }
```

**Comment by RichardLindhout** [comment]
This still happens
![Scherm­afbeelding 2023-05-06 om 16 52 52](https://user-images.githubusercontent.com/6492229/236631582-02a8bea1-65e3-4dcd-b508-20e15565e6cf.png)

**Comment by david98** [comment]
I had the same error on on iOS and solved it like this:

```diff
--- a/node_modules/@gorhom/bottom-sheet/src/hooks/useGestureEventsHandlersDefault.tsx
+++ b/node_modules/@gorhom/bottom-sheet/src/hooks/useGestureEventsHandlersDefault.tsx
@@ -21,7 +21,7 @@ type GestureEventContextType = {
   isScrollablePositionLocked: boolean;
 };
 
-const dismissKeyboardOnJs = runOnJS(Keyboard.dismiss);
+const dismissKeyboard = Keyboard.dismiss
 
 export const useGestureEventsHandlersDefault: GestureEventsHandlersHookType =
   () => {
@@ -298,7 +298,7 @@ export const useGestureEventsHandlersDefault: GestureEventsHandlersHookType =
                 absoluteY > WINDOW_HEIGHT - animatedKeyboardHeight.value
               )
             ) {
-              dismissKeyboardOnJs();
+              runOnJS(dismissKeyboard)();
             }
           }
```

I used [patch-package](https://www.npmjs.com/package/patch-package) to apply the fix.

**Comment by robinlindhout** [comment]
@david98 this patch crashed Android on startup for me

**Comment by david98** [comment]
> @david98 this patch crashed Android on startup for me

I did get some crashes during use, but I got those before patching too. In the end, I just reverted to reanimated v2 as I kept having issues.

**Comment by gabisanmartin12** [comment]
Same issue!!!!

**Comment by gorhom** [comment]
this should be resolved with the latest releases on `v4` and `v5`
