### ISSUE TITLE
[v5] | [v2] (web) BottomSheet doesn't work with React strict mode enabled

### ISSUE THREAD

**Issue by MoOx** [gorhom/react-native-scroll-bottom-sheet#1455]
# Bug

I tried BottomSheet + BottomSheetScrollView a while ago and didn't find a way to have this working (ref [#11](https://github.com/gorhom/react-native-bottom-sheet/pull/1150#issuecomment-1404845884) )

I saw the PR merged recently so I just tried v5. No luck... until I found a clue.

I am currently using Next.js + RNWeb but this is not the source of the issue.

I found that react strict mode is causing trouble.

Using `reactStrictMode: false` in `next.config.js` solved the problem.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 5.0.0-alpha.3   |
| next                    | 13.1.1   |
| react-native-web                    | 0.19.6   |
| react-native-reanimated         | 3.3.0   |
| react-native-gesture-handler    | 2.12.0   |

## Steps To Reproduce

1. Use the example in https://gorhom.github.io/react-native-bottom-sheet/components/bottomsheetscrollview/
2. Enable React Strict Mode
3. You will 3 issues in dev console mentionning `findDOMNode is deprecated in StrictMode`

<details>

<summary>Warning: findDOMNode is deprecated in StrictMode. </summary>

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of AnimatedComponent(ScrollView) which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
div
View
_classCallCheck@
_c
_classCallCheck@
_classCallCheck@
GestureDetector
ScrollableContainer
BottomSheetScrollView
div
View
_classCallCheck@
_classCallCheck@
GestureDetector
BottomSheetDraggableViewComponent
div
View
_classCallCheck@
div
View
_classCallCheck@
div
View
BottomSheetContainerComponent
BottomSheetGestureHandlersProvider
BottomSheet
div
View
App
NoSSR
Suspense
div
View
GestureHandlerRootView
App
_classCallCheck@
PathnameContextProviderAdapter
PureComponent@
ReactDevOverlay
_classCallCheck@
AppContainer
Root
```

</details>

Describe what you expected to happen:

1. BottomSheet should work with strict mode enabled

## Reproducible sample code

See this Next.js code sandbox, that has react strict mode disabled 

https://codesandbox.io/p/sandbox/next-js-playground-forked-y2frw9?welcome=true

(urls need to be opened in the sandbox link above)

Works (no strict mode) `https://y2frw9-3000.csb.app/`
Don't work (strict mode on using `<React.StrictMode>`) `https://y2frw9-3000.csb.app/donotwork`

**Comment by MoOx** [comment]
Related to https://github.com/software-mansion/react-native-reanimated/issues/4802

**Comment by MoOx** [comment]
FYI, it's still an issue

**Comment by MoOx** [comment]
@gorhom any plan to support React strict mode ?

**Comment by MoOx** [comment]
FYI, the reanimated upstream issue has been fixed.

What is causing the issue here is this implementation detail https://github.com/gorhom/react-native-bottom-sheet/blob/v5/src/utilities/getRefNativeTag.web.ts#L5

Alternative to this could would be to use a ref directly, see https://react.dev/reference/react-dom/findDOMNode#alternatives

**Comment by junaid-ahmed7** [comment]
I'm still seeing these three issues when using StrictMode. 

`(NOBRIDGE) ERROR  Warning: findHostInstance_DEPRECATED is deprecated in StrictMode. findHostInstance_DEPRECATED was passed an instance of AnimatedComponent(Wrap) which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://react.dev/link/strict-mode-find-node`

`(NOBRIDGE) ERROR  Warning: findNodeHandle is deprecated in StrictMode. findNodeHandle was passed an instance of Wrap which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://react.dev/link/strict-mode-find-node`

`(NOBRIDGE) ERROR  Warning: findHostInstance_DEPRECATED is deprecated in StrictMode. findHostInstance_DEPRECATED was passed an instance of Wrap which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://react.dev/link/strict-mode-find-node`

### Environment info
| Library | Version |
|--------|--------|
| expo | 52.0.20 |
| react-native | 0.76.5 |
| @gorhom/bottom-sheet | 5.0.6 |
| react-native-reanimated | 3.16.1 |
| react-native-gesture-handler | 2.20.2 |

**Comment by MaxTheTurtle0** [comment]
also still having this issue

**Comment by itsUndefined** [comment]
Also having the issue @MoOx can this be re-opened?

**Comment by WaldoJeffers** [comment]
Same thing. Maybe this can be re-opened? Or should we create a new issue instead?

**Comment by KiddoV** [comment]
Any update on this?

**Comment by lasfito** [comment]
got this issue today
