### ISSUE TITLE
[v4] BottomSheetModal appears beneath the screen

### ISSUE THREAD

**Issue by z1haze** [gorhom/react-native-scroll-bottom-sheet#1644]
# Bug

When using `createNativeStackNavigator` and specifying that a screen should open in a `modal` or `transparentModal`, your provider will inject the modal beneath the screen, making it impossible to interact with. When I say beneath, i am referring to z-space, or stacking context. The expected result is the modal would appear ontop of the screen, just like it does when using `createStackNavigator`.

I can't be bothered to spend a bunch of time to recreate a scenario online, for this to probably go ignored. but in the off chance you do look at this and notice quickly that there is indeed an issue, fixing it would be much appreciated!

attaching a video as evidence of the issue.

https://github.com/gorhom/react-native-bottom-sheet/assets/6024725/f57b0e47-f6c5-449c-b911-b04a829a97e9

**Comment by z1haze** [comment]
relates to #832, but it definitely isnt fixed.

**Comment by ljukas** [comment]
You can prevent this @z1haze by using the `containerComponent` prop on the `BottomSheetModal` like this:

```
<BottomSheetModal containerComponent={(props) => <FullWindowOverlay>{props.children</FullWindowOverlay>} />
```

Remember this only needs to be done on iOS

**Comment by z1haze** [comment]
> You can prevent this @z1haze by using the `containerComponent` prop on the `BottomSheetModal` like this:
> 
> ```
> <BottomSheetModal containerComponent={(props) => <FullWindowOverlay>{props.children</FullWindowOverlay>} />
> ```
> 
> Remember this only needs to be done on iOS

It looks like it did solve the problem, so thanks for the tip. Do you understand why this is needed? Also, I ended up solving this a different way too, by using `containedTransparentModal` instead of `transparentModal` on the presentation. I don't particularly know what happens behind the scenes on this, but it works.

**Comment by galgord** [comment]
I have the same issue

**Comment by ljukas** [comment]
I think it has to do with iOS rendering modals above everything else. And BottomSheetModals renders from the provider and not the screen itself. So when you render a BottomSheetModal it will render outside the modal-screen, and therefore render behind it. If you instead use a `transparentModal` or `containedModal` these enforce the same render-above rules as a modal does. Hence why you then get your BottomSheetModal above them. 

You can try this by wrapping your component inside the `modal`-screen with a BottomSheetModalProvider and then rendering your BottomSHeetModal inside it

**Comment by z1haze** [comment]
That  indeed the cause of the issue, but your proposed work around is hacky at best. No one wants to include a provider every time they want to use a sheet as it defeats the purpose and can cause issues if it ever gets included more than once.

That said, I think the fix here is that the components being rendered, in this case, a bottom sheet modal, should be conditionally wrapped in a FullWindowOverlay on iOS, like already suggested

**Comment by ljukas** [comment]
To be clear, I do not propose that as a solution, just mentioned that i can be confirmed by doing that. Me myself have went with using `presentation: 'containedModal'` on the my screen-modals to circumvent this issue. Because when you use the `FullWindowOverlay` solution you can no longer inspect that component using the development tools since the "inspect" window renders below the `FullWindowOverlay`.

So my purposed solution to this and what I use can be seen in this code snipped:

```tsx
<Stack.Screen
     name={'modal-containing-bottom-sheet-modal'}
     options={{
        presentation: 'containedModal',
     }} 
 />
 ```

**Comment by z1haze** [comment]
Fair reasoning. I am using that approach too, on screens, but for other libraries, like notification libraries that you want to appear in top of ios models, those are not in screens and therefore the FullWindowOverlay is a solution. Just in case you ever run into that

**Comment by z1haze** [comment]
No wonder things don't get fixed in this library.

**Comment by romantseg** [comment]
this issue is still present in the latest version and IMHO would be great to get fixed

**Comment by giaset** [comment]
Adding `containerComponent={({ children }) => <FullWindowOverlay>{children}</FullWindowOverlay>}` to my `BottomSheetModal` weirdly causes the modal to flicker on open


https://github.com/gorhom/react-native-bottom-sheet/assets/2816603/3bdbb736-ac4b-4413-8662-9e9796f99104

**Comment by giaset** [comment]
Fixed by wrapping it in useCallback and only setting it on iOS

```
const containerComponent = useCallback((props: any) => <FullWindowOverlay>{props.children}</FullWindowOverlay>, []);

return <BottomSheetModal containerComponent={IS_IOS ? containerComponent : undefined}>...</BottomSheetModal>
```

**Comment by SaraChicaD** [comment]
I wasn't able to get it to work by changing to `react-navigation/stack`, when I used `FullWindowOverlay` I the bottom sheet ended up not full width and floating in the middle of the screen, even when I tried styling it. Changing the stack modal presentation prop created other issues for me so I couldn't do that. 

It's really too bad because this looks great I just can't get the sheet content to be _on top_ of the screen content.

**Comment by christophby** [comment]
Did you also solve it on **Android**?
`FullWindowOverlay` is only available in iOS

**Comment by Kaique292** [comment]
> containerComponent={IS_IOS ? containerComponent : undefined}>...</BottomSheetMod

Same here...

**Comment by Kaique292** [comment]
The prop $modal and nothing, is same

**Comment by Gautamvaishnav-git** [comment]
```ts
<BottomSheet
        ref={bottomSheetRef}
        snapPoints={snapPoints}
        enableDynamicSizing={false}
        onChange={handleSheetChange}
        enablePanDownToClose={true}
        index={-1}
        containerStyle={{ <<<<<<<<<<<<<<< 
          zIndex: 999, <<<<<<<<<<<<<<< 
        }} <<<<<<<<<<<<<<< 
      >
.....
</BottomSheet>
```


This worked for me 😃, IDK this is correct way to do it or not.

**Comment by Karthik-B-06** [comment]
Does the backdrop component work the same? Because I am not able to add the backdrop component.

**Comment by mrmuke** [comment]
I need a workaround for android as well...

**Comment by Themrpie** [comment]
What did the trick for me was just wrapping my component using BottomSheet with a Portal component from react-native-paper.

**Comment by cpojer** [comment]
Pretty much all the comments here are bad workarounds. The actual solution is to wrap your modal with a `<BottomSheetModalProvider>`. By wrapping I mean putting the modal provider around whichever is the "root" node of your modal, so most likely a container, view or scroll view element.

That will render the bottom sheet above the modal, without any hacks.

**Comment by R0ixy** [comment]
Solved it on both ios and android by using [ZView](https://github.com/intergalacticspacehighway/react-native-z-view)  instead of FullWindowOverlay

```
<BottomSheetModal containerComponent={ModalContainer}>
...
</BottomSheet>
```

```
const ModalContainer = ({ children }: { children?: React.ReactNode }) => (
  <ZView>
    <View style={{ width: deviceWidth, height: deviceHeight }}>{children}</View>
  </ZView>
);
```

**Comment by FabienGreard** [comment]
An other naive solution which has some drawback is to wrap everything inside a Modal from react native, works both on IOS and Android but you will loose the principle of having multiple bottomSheet below the provider, which is probably Ok for most apps

```
import { Modal } from 'react-native';
import {
  BottomSheetModalProvider,
  BottomSheetModal,
  BottomSheetView,
} from '@gorhom/bottom-sheet';

... 
<Modal>
   <BottomSheetModalProvider>
     <BottomSheetModal>
       <BottomSheetView>
...
       </BottomSheetView>
    <BottomSheetModal>
  <BottomSheetModalProvider>
<Modal>
```

**Comment by thechaudharysab** [comment]
For me what https://github.com/gorhom/react-native-bottom-sheet/issues/1644#issuecomment-2851151422 mentioned, wrapping the toast in `Portal` works. Just wrap your main Bottom Sheet component in `<Portal>...</Portal>` import from  `import { Portal } from "@gorhom/portal"` which comes package in `@gorhom/bottom-sheet` I have v5.0.6.

**Comment by dilpreetsinghoi** [comment]
Hey guys, Im unable to raise an issue...its getting closed by github again and again, so sharing my query here in the comment section, would appreciate the help !

I’ve been trying to open React Native screens on top of an active BottomSheet, but haven’t found a good way to achieve it yet.

Essentially, I want to push a new screen to my navigation stack while keeping the BottomSheet open in the background — meaning the BottomSheet should hide behind the new screen, and when I close that screen, the BottomSheet should still be there as it was.

Is there a straightforward way to implement this, or is this kind of behavior too complex to achieve?

**Comment by mayvagio2016** [comment]
@dilpreetsinghoi there is nothing to address the issues now.
