### ISSUE TITLE
[Bug]: Error for not having flashlist even when not using the flashlist component

### ISSUE THREAD

**Issue by dannyhw** [gorhom/react-native-scroll-bottom-sheet#1968]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

iOS, Android, Web

### What happened?

When using version 5 without flashlist installed this error causes the app to crash

You need to install FlashList first,yarn install @shopify/flash-list, js engine: hermes

Since the files are all barrel files every file will run even if you don't import them so this would only be fixed by

removing the export from:
src/components/bottomSheetScrollable/index.ts and here src/index.ts

### Reproduction steps

- setup bottom sheet and don't install flashlist
- import scrollable (not flashlist)
- crashes

### Reproduction sample

https://snack.expo.dev/@dannyhw/bottom-sheet---issue-reproduction-template

### Relevant log output

```shell
You need to install FlashList first, `yarn install @shopify/flash-list`
  Evaluating @gorhom/bottom-sheet.js
  Evaluating App.js
  Loading App.js
```

**Comment by FernandoAcTr** [comment]
Same issue here

**Comment by gorhom** [comment]
this should be resolved with [v5.0.2](https://github.com/gorhom/react-native-bottom-sheet/releases/tag/v5.0.2). feel free to re-open

**Comment by sleekLancelot** [comment]
> this should be resolved with [v5.0.2](https://github.com/gorhom/react-native-bottom-sheet/releases/tag/v5.0.2). feel free to re-open

Hi, I still face the same issue on v5.0.2, i need it for the dynamic sizing bit.
`You need to install FlashList first, yarn install @shopify/flash-list, js engine: hermes`

**Comment by dannyhw** [comment]
@sleekLancelot I recommend double checking you have got the right version (check lockfile) and clearing the cache because it should only throw the error now if you use the flashlist scrollable.

**Comment by sleekLancelot** [comment]
> @sleekLancelot I recommend double checking you have got the right version (check lockfile) and clearing the cache because it should only throw the error now if you use the flashlist scrollable.

Had to delete it, reinstall and rebuild again. For some reason it works now.
