### ISSUE TITLE
[Bug]: onAnimate executed 2 times if autofocus is set true on the BottomSheetTextInput

### ISSUE THREAD

**Issue by kawasakime** [gorhom/react-native-scroll-bottom-sheet#2012]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

iOS, Android

### What happened?

If you set the prop autoFocus={true} in the BottomSheetTextInput, then due to the opening of the keyboard, onAnimate executed twice, which leads to backdrop lags (the appearance animation occurs twice). Android suffers to a greater extent, since iOS does not have such a visual problem.

We currently have version 4.6.4 in the project and there is no such problem.

https://github.com/user-attachments/assets/877522cd-1c5e-417a-afba-b74f438738ea

### Reproduction steps

- add a BottomSheetTextInput inside the BottomSheet component.
- add prop autoFocus={true}
- open bottom sheet

### Reproduction sample

https://snack.expo.dev/q8k_w0qzlr4rouvpqrsum

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
To address the issue of the backdrop animation occurring twice due to keyboard opening, we need to modify the `useKeyboard` hook and the `BottomSheet` component. The main changes involve adding a debounce mechanism to prevent rapid consecutive keyboard events from triggering multiple animations.

In the `useKeyboard` hook, we'll introduce a debounce timer to ensure that only the last keyboard event within a short time frame is processed. In the `BottomSheet` component, we'll adjust the animation logic to account for this debounced keyboard event.

I also created pull request: https://github.com/gorhom/react-native-bottom-sheet/pull/2013

> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by kawasakime** [comment]
In version 5.0.6 the problem remained. At the same time, funny behavior results.
1) If you do autofocus with a delay (in my case 200ms), then the bottom sheet will most likely close immediately. Sometimes there is no lag with the backdrop, but more often there is lag, or even more likely the bottom sheet simply closes.
2) If autofocus is without a delay, then onAnimate still fires twice, which causes backdrop lag

Only Android


https://github.com/user-attachments/assets/ef570507-565f-48f4-a7c1-d3323404ef77


https://github.com/user-attachments/assets/21580822-6f54-49d9-83c4-57ffc92b0899

**Comment by Osamasomy** [comment]
In my case, when I set autoFocus = true and navigate to the screen where it is used, the sheet opens automatically even if the index is set to -1.
