### ISSUE TITLE
[Bug]: Sheet not showing after upgrading react native from 0.75.4 -> 0.76.0 

### ISSUE THREAD

**Issue by LA-Johan** [gorhom/react-native-scroll-bottom-sheet#2015]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

iOS, Android

### What happened?

Did not have new architecture turned on for 0.75.4. Version sheet version 5.0.5.

Code:

```
import React, { FC, PropsWithChildren, useEffect, useRef } from "react"
import { BottomSheetModal, BottomSheetScrollView, useBottomSheetSpringConfigs } from "@gorhom/bottom-sheet"
import { useSafeAreaInsets } from "react-native-safe-area-context"
import { DropdownProps } from "../../../shared-client/props/DropdownProps"
import { ReduceMotion, useReducedMotion, type WithTimingConfig } from "react-native-reanimated"
import { Platform } from "react-native"
import { dismissKeyboard } from "../../utils/keyboardUtils"
import { View } from "./View"
import { BACKGROUND_COLOR, OVERLAY_COLOR, TEXT_DARK, useColorString } from "../../../shared-client/constants/colors"

export const Dropdown: FC<DropdownProps> = ({ children, dropdownContent, openState: [open, setOpen] }) => {
  const bottomSheetModalRef = useRef<BottomSheetModal>(null)
  useEffect(() => {
    if (open) {
      bottomSheetModalRef.current?.present()
      dismissKeyboard()
    } else {
      bottomSheetModalRef.current?.dismiss()
    }
  }, [open])
  return (
    <>
      {children}
      <BottomSheetModal
        ref={bottomSheetModalRef}
        backgroundStyle={{ backgroundColor: useColorString(BACKGROUND_COLOR) }}
        handleIndicatorStyle={{ backgroundColor: useColorString(TEXT_DARK) }}
        enableDynamicSizing
        onDismiss={() => setOpen(false)}
        animationConfigs={useAnimationConfig()}
        backdropComponent={() => (
          <View
            laStyle={{ position: { top: 0, bottom: 0, left: 0, right: 0 }, flex: 1, background: OVERLAY_COLOR }}
            onTap={() => setOpen(false)}
          />
        )}
      >
        <InternalView>{dropdownContent}</InternalView>
      </BottomSheetModal>
    </>
  )
}

/*
  There's a bug in BottomSheet which means that sheets will fail to open when reduce motion is enabled. Manually
  providing an animation config with `reduceMotion: ReduceMotion.Never` fixes this, but it does introduce a bit
  of jank when dismissing the sheet. This is a tradeoff we're willing to make for the sake of sheets at least
  working when reduce motion is enabled.

  @see https://github.com/gorhom/react-native-bottom-sheet/issues/1560
*/
const useAnimationConfig = (): WithTimingConfig | undefined => {
  const reduceMotionEnabled = useReducedMotion()
  const overrideConfig = useBottomSheetSpringConfigs({
    damping: 500,
    stiffness: 1000,
    mass: 3,
    overshootClamping: true,
    restDisplacementThreshold: 10,
    restSpeedThreshold: 10,
    reduceMotion: ReduceMotion.Never,
  })
  return Platform.OS === "ios" && reduceMotionEnabled ? overrideConfig : undefined
}

const InternalView: FC<PropsWithChildren> = ({ children }) => {
  const insets = useSafeAreaInsets()
  return (
    <BottomSheetScrollView overScrollMode={"never"}>
      {children}
      <View laStyle={{ height: insets.bottom }} />
    </BottomSheetScrollView>
  )
}
```

### Reproduction steps

<img width="416" alt="Screenshot 2024-10-30 at 11 02 59 AM" src="https://github.com/user-attachments/assets/0e589793-aaf4-49cd-bac7-97b25d50f0f3">
<img width="397" alt="Screenshot 2024-10-30 at 10 59 40 AM" src="https://github.com/user-attachments/assets/27daffca-a133-41db-a22d-71390921e93a">

<img width="412" alt="Screenshot 2024-10-30 at 10 29 24 AM" src="https://github.com/user-attachments/assets/8003fe42-7cc2-46af-84ff-b4176bda69a6">
<img width="384" alt="Screenshot 2024-10-30 at 10 29 20 AM" src="https://github.com/user-attachments/assets/788fd813-05bb-4d1d-bc45-c4d391209785">

Could not reproduce in snack. 

### Reproduction sample

https://snack.expo.dev/vzyoxpZc5yzsyBqVLeISU

**Comment by K3vlarUK** [comment]
Have you managed to get any time on this @gorhom ? Having same issue trying out 0.76.1 from 0.75.3

**Comment by LA-Johan** [comment]
Yes, I'm still seeing it on 0.76.1 as well. Let me know if I can provide any other information.

**Comment by fobos531** [comment]
it's worth nothing that this issue doesn't appear if dynamic sizing is turned off. So, likely a bug related to dynamic sizing.

**Comment by inthisar-hamza** [comment]
@fobos531 it's not working even it's turned off

**Comment by LA-Johan** [comment]
@fobos531 I tried without dynamic sizing and still saw the issue (possible the hot reload didn't work and code was stale)

**Comment by vorn-dev-ni** [comment]
same same

**Comment by LA-Johan** [comment]
@gorhom is it possible to get a status update on this issue?

**Comment by fobos531** [comment]
Hello everyone, can you try the following fix to see if it fixes the issue for you?

https://github.com/gorhom/react-native-bottom-sheet/pull/2010#issuecomment-2474832680

**Comment by gorhom** [comment]
it should be fixed with the latest release!

**Comment by inthisar-hamza** [comment]
It's still not working on v5.0.6 and react native v76! still doesn't shows up
