### ISSUE TITLE
[Bug]: Android - Can't click Pressables inside Scrollview that is alongside my BottomSheet both inside a GestureHandlerRootView

### ISSUE THREAD

**Issue by r-obeen** [gorhom/react-native-scroll-bottom-sheet#2099]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

Android

### What happened?

When I have a BottomSheet into my ScrollView and I scroll a bit, my Pressables in my ScrollView are not responding anymore... If I remove the BottomSheet component, it works again... 

It only happens on Android (physical phone, I have tested on Android 14). It works fine on physical iPhone, iPhone simulator and Android Simulator 🤔.

Any idea why that happens ?

Demo (sorry, I recorded on a very slow Android phone, I've tested on fast Android phone, same issue) :
https://github.com/user-attachments/assets/53510520-63a6-4dab-8307-55871a95c80c

### Reproduction steps

- Open the Snack on a real Android device (using Expo Go)
- Before scrolling down, press on Button 1 or Button 2, it should open the sheet
- Scroll down and try to press Button 1 or Button 2 again, it will not open the sheet anymore

_If you remove the`<BottomSheet>` component (with its children), button presses will work fine, even after scroll_

### Reproduction sample

https://snack.expo.dev/@robeen/bottomsheet-press-issue-after-scroll?platform=android

**Comment by Chanki-Min** [comment]
I'm experiencing the same issue. For the child components of the ScrollView, the onPress callbacks work correctly for any components that were initially rendered at the top (the initial scroll position). 

However, if I scroll down and tap on components that were not visible in the initial scroll position (In other words, components ware hidden), their onPress callbacks do not fire.

**Comment by CHOIMINSEOK** [comment]
FYI; 
If you set `enableContentPanningGesture` as false in `BottomSheetModal`, it blocks all touch events in ScrollableContents after the content scrolls down. BottomSheetModal makes scroll handler bridge (`BottomSheetDraggableView`) internally, but when `enableContentPanningGesture=false`, the bridge is replaced by normal Animated.View,  which seems to break Android touch chains in android real device

```ts
    // render
    const DraggableView = enableContentPanningGesture
      ? BottomSheetDraggableView
      : Animated.View;
```
https://github.com/gorhom/react-native-bottom-sheet/blob/7bfe7ae807b135ffd8e4fcfeb6beb38998b65165/src/components/bottomSheet/BottomSheet.tsx#L1870

**Comment by junaid-ahmed7** [comment]
> I'm experiencing the same issue. For the child components of the ScrollView, the onPress callbacks work correctly for any components that were initially rendered at the top (the initial scroll position).
> 
> However, if I scroll down and tap on components that were not visible in the initial scroll position (In other words, components ware hidden), their onPress callbacks do not fire.

I am also experiencing the same issue as @r-obeen - where it does not matter if the component was initially rendered at the top or not, after scrolling all onPress callbacks do not fire unless you scroll back to the top again.

Anyone have any luck with a fix/workaround?

**Comment by r-obeen** [comment]
@junaid-ahmed7 I don't know why nor how but the issue resolved by itself surprisingly...

**Comment by junaid-ahmed7** [comment]
@r-obeen Interesting. I'm still seeing the same issue. Would you mind sharing the versions you are running where the issue resolved itself for:
- expo
- react-native
- @gorhom/bottom-sheet
- react-native-reanimated
- react-native-gesture-handler

Thank you

**Comment by junaid-ahmed7** [comment]
For anyone dealing with this issue, it's addressed and the solution is in the docs here: https://gorhom.dev/react-native-bottom-sheet/troubleshooting#pressables--touchables-are-not-working-on-android

**Comment by perttuvirkki** [comment]
@r-obeen I have the exact same issue still, also interested in what versions you got which work?

**Comment by devartwa** [comment]
I'm still facing the same problem on Android. Any solution?

**Comment by MichaelSebsbe** [comment]
> I'm still facing the same problem on Android. Any solution?

Wrapping the ScrollView in a View worked for me
