### ISSUE TITLE
[Bug]: findNodeHandle i not supported on web and this is crashing all react native web apps

### ISSUE THREAD

**Issue by idrisssakhi** [gorhom/react-native-scroll-bottom-sheet#2237]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

Web

### What happened?

The bottom sheets do not work anymore on web on latest expo + react native versions

### Reproduction steps

* have any bottom sheet component rendered on react-native web app
* expo 52.0.44

### Reproduction sample

https://snack.expo.dev/@idris-timeleft/f615a2

### Relevant log output

```shell
index.js:12 Uncaught Error: findNodeHandle is not supported on web. Use the ref property on the component instead.
    at findNodeHandle (index.js:12:9)
    at useScrollHandler.web.js:28:35
    at commitHookEffectListMount (react-dom.development.js:23189:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24965:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24930:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24917:7)
    at commitPassiveMountEffects (react-dom.development.js:24905:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27078:3)
    at flushPassiveEffects (react-dom.development.js:27023:14)
    at react-dom.development.js:26808:9
```

**Comment by idrisssakhi** [comment]
issue is related to "react-native-web": "0.20.0",

**Comment by erickreutz** [comment]
Running into this as well. react-native-web@0.20.0 deprecated findNodeHandle (as it should). BottomSheet will need to update it's code not to use it.

**Comment by ammarfaris** [comment]
+1

_In React 19, findNodeHandle has been removed. This function, previously used to access the native DOM node instance from a React component, is no longer supported due to changes in React's internal architecture and its approach to handling the DOM. The removal of findNodeHandle aligns with React's shift towards more modern and efficient ways of interacting with the DOM._

**Comment by giaset** [comment]
+1 -- completely breaks on web if we use BottomSheetScrollView

**Comment by giaset** [comment]
Here is my patch that got it working on web

[@gorhom+bottom-sheet+5.1.2.patch](https://github.com/user-attachments/files/20024191/%40gorhom%2Bbottom-sheet%2B5.1.2.patch)

**Comment by doubleedev** [comment]
Is there a fix for this yet ?

"@gorhom/bottom-sheet": "^5.1.2",

**Comment by gorhom** [comment]
it should be fixed in `v5.1.3`, thanks for reporting it

**Comment by idrisssakhi** [comment]
@gorhom not completly resolved but great work, the issue now is 
```componentOrHandle.getNativeScrollRef is not function ``` hapens only when we use scrollables
maybe we can reopen the bug for tracability wdyt ?

**Comment by shahshachi1** [comment]
Not completely resolved yet. I get an error saying it's in my measureSelf() of my ui-kitten-components+5.3.1

const measureSelf = () => {
         const node = (0, react_native_1.findNodeHandle)(ref.current);
-        react_native_1.UIManager.measureInWindow(node, onUIManagerMeasure);
+        if (node) react_native_1.UIManager.measureInWindow(node, onUIManagerMeasure);
     };

**Comment by btoo** [comment]
> [@gorhom](https://github.com/gorhom) not completly resolved but great work, the issue now is `componentOrHandle.getNativeScrollRef is not function ` hapens only when we use scrollables maybe we can reopen the bug for tracability wdyt ?

i'm getting this error too. here's a minimum reproduction: https://snack.expo.dev/@brme/playful-yellow-cashew

EDIT: i believe i've found the fix for this in https://github.com/gorhom/react-native-bottom-sheet/pull/2292
