### ISSUE TITLE
[Bug]: Switching keyboard types triggers unwanted close

### ISSUE THREAD

**Issue by goncalo1995** [gorhom/react-native-scroll-bottom-sheet#2430]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

iOS

### What happened?

Switching from text input to a numeric input (not the other way around) is cause the modal to close. I could not test in Android but happens in iOS.

### Reproduction steps

Could not make BottomSheetModal show in expo snack, this bug happens in my development build.

How to reproduce the bug:
1. Run this in Expo or bare React Native with @gorhom/bottom-sheet v4.4.5.
2. Open the sheet, focus the text input, then switch to the numeric input.

Example modal that causes the unwanted close:
<BottomSheetModal
        ref={sheetRef}
        index={0}
        snapPoints={snapPoints}
        onDismiss={() => console.log("Sheet dismissed")}
        keyboardBehavior="interactive"
        keyboardBlurBehavior="restore"
        enablePanDownToClose={false}
      >
        {/* Use BottomSheetScrollView or BottomSheetView */}
        <BottomSheetScrollView contentContainerStyle={{ padding: 20 }}>
          <Text style={{ marginBottom: 10 }}>Text Input:</Text>
          <BottomSheetTextInput
            style={{
              borderWidth: 1,
              borderColor: "#ccc",
              padding: 10,
              marginBottom: 20,
              borderRadius: 5,
            }}
            placeholder="Text input"
            value={textValue}
            onChangeText={setTextValue}
          />

          <Text style={{ marginBottom: 10 }}>Numeric Input:</Text>
          <BottomSheetTextInput
            style={{
              borderWidth: 1,
              borderColor: "#ccc",
              padding: 10,
              borderRadius: 5,
            }}
            placeholder="Numeric input"
            value={numberValue}
            onChangeText={setNumberValue}
            keyboardType="numeric"
          />
        </BottomSheetScrollView>
      </BottomSheetModal>

### Reproduction sample

https://snack.expo.dev/@cereja/mixed-inputs-bug-bottomsheet

### Relevant log output

```shell

```

**Comment by devshahoriar** [comment]
https://github.com/user-attachments/assets/1f16c914-0007-401c-83d2-d5e09cec2f04

how to solve this?

**Comment by shubhams-york** [comment]
+1

**Comment by ertucaglar** [comment]
+1

I have the same issue, the keyboard closes as soon as it is opened, if dynamic size is enabled

**Comment by eetzuh** [comment]
Same issue in v5.2.3, happens on Android too

**Comment by agueraXneuf** [comment]
+1

I think that It happens when the keyboard is visible and the bottom sheet modal fulfill the screen.
I find a quick fix it by setting `maxDynamicContentSize` prop. The aim is to avoid the modal to cover the entire screen when the keyboard is shown.

`maxDynamicContentSize={500}`

I'm pretty sure that using a fixed value is the wrong way because it depends on the screen size.
Maybe this small formula can help (based on the screen dimensions I used to test - iPhone 13 mini)

```
const REF_SCREEN_HEIGHT = 812;
const REF_MAX_HEIGHT = 500;
const {height} = Dimensions.get("screen");
const maxDynamicContentSize = height * REF_MAX_HEIGHT / REF_SCREEN_HEIGHT;
```

**But we still need to find a correct, clean fix !**

**Comment by jsellam** [comment]
Same issue on android and 5.1.6

**Comment by motudev** [comment]
Can reproduce this, when using 5.2.3, ios and snapPoints, no keyboard type and with `enableDynamicSizing={false}` with a minimal example of just this, which is the default setup in https://gorhom.dev/react-native-bottom-sheet/modal/usage:

```
<View>
  <Button
    onPress={handlePresentModalPress}
    title="click"
  />
  <BottomSheetModalProvider>
    <BottomSheetModal
      ref={bottomSheetModalRef}
      index={1}
      snapPoints={snapPoints}
      enableDynamicSizing={false}
      onChange={handleSheetChanges}>
      <BottomSheetTextInput style={styles.input} />
      <BottomSheetView style={styles.contentContainer}>
        <Text>Awesome 🎉</Text>
      </BottomSheetView>
    </BottomSheetModal>
  </BottomSheetModalProvider>
</View>
```

**Comment by gorhom** [comment]
should be fixed with v5.2.4

**Comment by eetzuh** [comment]
This still happens on Android v5.2.4. I am just focusing the input in bottom sheet modal which causes the sheet to reach the top of the screen and then it dismisses immediately

```
 const { handleSheetPositionChange } = useBottomSheetBackHandler(ref);
<BottomSheetModal
      ref={ref}
      onChange={handleSheetPositionChange}
      backdropComponent={BottomSheetModalBackdrop}
      keyboardBlurBehavior="restore"
      style={{ paddingHorizontal: 16 }}
      backgroundStyle={{
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        backgroundColor: Colors.greyscale.white[100],
        borderWidth: 1,
        borderColor: Colors.greyscale.grey[300],
        paddingHorizontal: 16,
        borderBottomColor: Colors.greyscale.grey[50],
        borderBottomWidth: 0,
      }}
    >
      <BottomSheetView style={{ paddingBottom: insets.bottom + 8 }}>
       {children}
       </BottomSheetView>
 </BottomSheetModal>
```

**Comment by klawijuice** [comment]
+1 same issue v5.2.4 on Pixel 8 api 34

**Comment by gorhom** [comment]
mm will investigate it tonight 🤦‍♂️

**Comment by mantu-bit** [comment]
facing same issue

**Comment by gorhom** [comment]
![Image](https://github.com/user-attachments/assets/05d0195a-e9be-4dc6-ba84-04f8f9d47ca0)

tested the issue use case on android with the fix and it worked as expected. please open another issue if you have another keyboard issue related with a repo sample

**Comment by rklf** [comment]
@gorhom For the issue to happen, the snapPoints need to cover enough of the screen so the keyboard doesn’t have space to open — it then auto-closes. Please try setting ``snapPoints={["70%", "100%"]}``. I also included "100%" to show that when the bottom sheet takes the full height, opening the keyboard **doesn’t** cause the issue. Can you reopen and give it a try?

https://github.com/user-attachments/assets/8af141e0-f3ed-46df-bceb-d1d2b1c00c6f

**Comment by iffa** [comment]
I am also seeing a dynamic height bottom sheet with a text input autoclosing when it has opened up, v5.2.4:

https://github.com/user-attachments/assets/698cc5d9-48f2-4f42-b6a4-4b96280b698f

**Comment by klawijuice** [comment]
https://github.com/user-attachments/assets/0d64e208-4920-4481-b1d9-de9a710b8bb6

i have same issue +1

and BottomSheetFlatList don't scroll

android api 34 
RN 0.79.6
New Arch True
"@gorhom/bottom-sheet": "^5.2.4",

**Comment by DmytroMelnyk26** [comment]
+1
"expo": "53.0.22",
"@gorhom/bottom-sheet": "^5.2.4",
"react-native": "0.79.5",

I also noticed that this does not happen if `keyboardBehavior="extend"`
