### ISSUE TITLE
[Bug]: BottomSheet flickers and freezes when slowly closing a modal window on native devices in a web browser.

### ISSUE THREAD

**Issue by kjkTommy** [gorhom/react-native-scroll-bottom-sheet#2510]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

Web

### What happened?

When slowly closing a modal window in a web browser on native devices, the following error occurs:

- BottomSheet starts flickering and getting cut off.

- When capturing a modal window and gradually collapsing it, BottomSheet sometimes gets stuck and displays incorrectly.

https://github.com/user-attachments/assets/2028c402-0759-4a7d-9c6c-9c3c14d4ccd9

### Reproduction steps

- Open the web version of the app on iOS or Android.

- Open BottomSheet.

- Start slowly closing the modal window by swiping down.

- Observation: BottomSheet begins to flicker, freeze, and become truncated.

- Expectation: BottomSheet should remain stable and render correctly.

### Reproduction sample

https://snack.expo.dev/@kjktommy/bottom-sheet---issue-reproduction-template

### Relevant log output

```shell
No relevant logs
```

**Comment by adam-sajko** [comment]
https://github.com/software-mansion/react-native-reanimated/issues/8228

@gorhom CC

**Comment by exzos28** [comment]
it's been fixed in the latest library version

**Comment by draco961** [comment]
You mean version "[5.2.6](https://github.com/gorhom/react-native-bottom-sheet/releases/tag/v5.2.6)" ? I still have the problem with that version on Android
